### PR TITLE
finish part1

### PR DESCRIPTION
**Pull request by bibbygreen**
陳宜群
http://52.89.165.57:8000/api/attractions?page=1
http://52.89.165.57:8000/api/attractions?page=0&keyword=劍潭
http://52.89.165.57:8000/api/attractions?page=0&keyword=北
http://52.89.165.57:8000/api/attraction/10
http://52.89.165.57:8000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- images field should be an array containing image URLs for each attraction.
- response format of http://52.89.165.57:8000/api/attraction/10 is incorrect.

**Comment by bibbygreen** [comment]
上述兩點已修正

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by cwpeng** [comment]
Merge pull request after review approval.

**Pull request merged**
