### PR TITLE
finish userApi and PyJWT

### PR DESCRIPTION
**Pull request by bibbygreen**
陳宜群
http://52.89.165.57:8000
http://52.89.165.57:8000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- We should send request with JSON format data in request body to User APIs.
- We should check user sign-in status by calling User API, not just check localStorage in the front-end. (how about I put any text in localStorage through developer tools?)

**Comment by bibbygreen** [comment]
already modified request body format and check user status by calling API

**Review by cwpeng — CHANGES_REQUESTED** [review]
Response format of User API should align with API specs.

**Comment by bibbygreen** [comment]
Response format 已修正
謝謝老師

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
